# Generated by Django 5.2.17 on 2026-09-30 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề block')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Tự động tạo bởi AI/Thuật toán')),
                ('is_locked', models.BooleanField(default=False, help_text='Khóa block để thuật toán sắp lịch tự động không dịch chuyển thời gian', verbose_name='Đã khóa (không ghi đè)')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú thêm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='tasks.task', verbose_name='Công việc liên kết')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Block lịch',
                'verbose_name_plural': 'Danh sách Block lịch',
                'ordering': ['start_time'],
            },
        ),
    ]
