# Generated by Django 5.2.17 on 2026-10-03 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0001_initial"),
        ("tasks", "0002_alter_task_estimated_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusyPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Hoạt động / ca làm"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Bắt đầu")),
                ("end_time", models.DateTimeField(verbose_name="Kết thúc")),
                (
                    "repeats_weekly",
                    models.BooleanField(
                        default=False, verbose_name="Lặp lại hằng tuần"
                    ),
                ),
                (
                    "repeat_until",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Lặp đến ngày (để trống = không giới hạn)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="scheduleblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="schedule_end_after_start",
            ),
        ),
        migrations.AddField(
            model_name="busyperiod",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="busy_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="busyperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="busy_end_after_start",
            ),
        ),
    ]
