# Generated by Django 5.2.17 on 2026-09-30 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('WORK', 'Làm việc / Học tập (25m)'), ('SHORT_BREAK', 'Nghỉ ngắn (5m)'), ('LONG_BREAK', 'Nghỉ dài (15m)')], default='WORK', max_length=20, verbose_name='Loại phiên')),
                ('duration_minutes', models.PositiveIntegerField(default=25, verbose_name='Thời lượng (phút)')),
                ('start_time', models.DateTimeField(verbose_name='Bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
                ('completed', models.BooleanField(default=True, verbose_name='Hoàn thành trọn vẹn')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú phiên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='tasks.task', verbose_name='Công việc thực hiện')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiên Pomodoro',
                'verbose_name_plural': 'Danh sách phiên Pomodoro',
                'ordering': ['-start_time'],
            },
        ),
    ]
