# Generated by Django 5.2.17 on 2026-10-03 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pomodoro", "0001_initial"),
        ("tasks", "0002_alter_task_estimated_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pomodorosession",
            name="elapsed_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="running_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pomodorosession",
            name="target_minutes",
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddConstraint(
            model_name="pomodorosession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="one_active_pomodoro_per_user",
            ),
        ),
    ]
