# Generated by Django 5.2.17 on 2026-09-30 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề công việc')),
                ('description', models.TextField(blank=True, verbose_name='Chi tiết công việc')),
                ('priority', models.IntegerField(choices=[(1, 'Thấp'), (2, 'Trung bình'), (3, 'Cao'), (4, 'Khẩn cấp')], default=2, verbose_name='Độ ưu tiên')),
                ('estimated_duration', models.PositiveIntegerField(default=60, help_text='Ước tính số phút cần để hoàn thành', verbose_name='Thời lượng ước tính (phút)')),
                ('deadline', models.DateTimeField(verbose_name='Thời hạn (Deadline)')),
                ('status', models.CharField(choices=[('TODO', 'Cần làm'), ('IN_PROGRESS', 'Đang làm'), ('COMPLETED', 'Đã hoàn thành')], default='TODO', max_length=20, verbose_name='Trạng thái')),
                ('difficulty', models.IntegerField(choices=[(1, 'Dễ'), (2, 'Trung bình'), (3, 'Khó / Nặng não')], default=2, verbose_name='Độ khó')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Đã xếp vào lịch')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='courses.course', verbose_name='Môn học')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Công việc / Deadline',
                'verbose_name_plural': 'Danh sách công việc & Deadline',
                'ordering': ['deadline', '-priority'],
            },
        ),
    ]
