# Generated by Django 5.2.17 on 2026-10-03 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="estimated_duration",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Ước tính số phút cần để hoàn thành",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="Thời lượng ước tính (phút)",
            ),
        ),
    ]
