# Generated by Django 5.2.17 on 2026-10-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_reminders",
            field=models.BooleanField(
                default=True, verbose_name="Nhắc deadline qua email"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="study_end_hour",
            field=models.PositiveSmallIntegerField(
                default=22, verbose_name="Giờ kết thúc học"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="study_start_hour",
            field=models.PositiveSmallIntegerField(
                default=8, verbose_name="Giờ bắt đầu học"
            ),
        ),
    ]
