# Generated by Django 5.2.17 on 2026-10-03 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_email_reminders_user_study_end_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="daily_study_goal_hours",
            field=models.PositiveSmallIntegerField(
                default=4,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Mục tiêu học mỗi ngày (giờ)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="study_end_hour",
            field=models.PositiveSmallIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(23),
                ],
                verbose_name="Giờ kết thúc học",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="study_start_hour",
            field=models.PositiveSmallIntegerField(
                default=8,
                validators=[django.core.validators.MaxValueValidator(22)],
                verbose_name="Giờ bắt đầu học",
            ),
        ),
    ]
