# Generated by Django 5.2.17 on 2026-10-03 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.resources.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("tasks", "0002_alter_task_estimated_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Tên tài liệu"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Ghi chú ôn tập"),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="Link tài liệu"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.resources.models.resource_path,
                        verbose_name="Tệp tài liệu (tối đa 10 MB)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.course",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
