# Generated by Django 5.2.17 on 2026-09-30 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên môn học')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Mã môn học')),
                ('color', models.CharField(choices=[('#3B82F6', 'Xanh lam (Blue)'), ('#10B981', 'Xanh lá (Green)'), ('#F59E0B', 'Vàng hổ phách (Amber)'), ('#EF4444', 'Đỏ (Red)'), ('#8B5CF6', 'Tím (Purple)'), ('#EC4899', 'Hồng (Pink)'), ('#06B6D4', 'Xanh lơ (Cyan)'), ('#6B7280', 'Xám (Gray)')], default='#3B82F6', max_length=20, verbose_name='Màu sắc')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='Số tín chỉ')),
                ('instructor', models.CharField(blank=True, max_length=100, verbose_name='Giảng viên')),
                ('semester', models.CharField(default='Học kỳ 1', max_length=50, verbose_name='Học kỳ')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang học')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Danh sách môn học',
                'ordering': ['name'],
            },
        ),
    ]
