# Generated by Django 5.2.17 on 2026-09-30 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=255, verbose_name='Token URI')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, verbose_name='Client Secret')),
                ('scopes', models.TextField(default='https://www.googleapis.com/auth/calendar', verbose_name='Scopes')),
                ('calendar_id', models.CharField(default='primary', max_length=255, verbose_name='Google Calendar ID')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần đồng bộ gần nhất')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_token', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Google Calendar Token',
                'verbose_name_plural': 'Google Calendar Tokens',
            },
        ),
    ]
