# Generated by Django 5.2.17 on 2026-10-03 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.calendar_sync.fields


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_sync", "0001_initial"),
        (
            "scheduler",
            "0002_busyperiod_scheduleblock_schedule_end_after_start_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendartoken",
            name="expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="googlecalendartoken",
            name="access_token",
            field=apps.calendar_sync.fields.EncryptedTextField(
                verbose_name="Access Token"
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendartoken",
            name="client_secret",
            field=apps.calendar_sync.fields.EncryptedTextField(
                blank=True, verbose_name="Client Secret"
            ),
        ),
        migrations.AlterField(
            model_name="googlecalendartoken",
            name="refresh_token",
            field=apps.calendar_sync.fields.EncryptedTextField(
                blank=True, null=True, verbose_name="Refresh Token"
            ),
        ),
        migrations.CreateModel(
            name="CalendarExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(blank=True, max_length=64)),
                (
                    "block",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scheduler.scheduleblock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "google_id"), name="unique_calendar_export"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_busy", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "google_id"), name="unique_google_event"
                    )
                ],
            },
        ),
    ]
