# Generated by Django 5.2.17 on 2026-09-30 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('DEADLINE_RISK', 'Cảnh báo rủi ro trễ hạn'), ('DAILY_SUMMARY', 'Tóm tắt công việc trong ngày'), ('SCHEDULE_DENSITY', 'Phân tích mật độ lịch bận')], default='DAILY_SUMMARY', max_length=30, verbose_name='Loại phân tích')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề tóm tắt')),
                ('content', models.TextField(verbose_name='Nội dung phân tích của AI')),
                ('actionable_advice', models.TextField(blank=True, verbose_name='Lời khuyên hành động')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='Đã xem / Đã ẩn')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'Danh sách AI Insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
