# Generated by Django 5.2.17 on 2026-10-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinsight",
            name="context_fingerprint",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("LOW", "LOW"),
                    ("MEDIUM", "MEDIUM"),
                    ("HIGH", "HIGH"),
                    ("CRITICAL", "CRITICAL"),
                ],
                default="LOW",
                max_length=10,
                verbose_name="Mức rủi ro",
            ),
        ),
        migrations.AddField(
            model_name="aiinsight",
            name="source",
            field=models.CharField(
                default="rules", max_length=30, verbose_name="Nguồn phân tích"
            ),
        ),
    ]
